### ISSUE TITLE
Container fails to start: unknown directive "max_fails=3"

### ISSUE THREAD

**Issue by xthilakx** [openbridge/nginx#32]
**Describe the bug**
I am trying to use docker image `openbridge/nginx:latest` to run `wordpress:php7.1-fpm-alpine` on another container. 

I created a volume called `root` and mapped it to `/var/www/html` on the wordpress container and mapped the same volume to `/usr/share/nginx/html` in nginx container. 

**My Dockerfile:**
```Dockerfile
FROM openbridge/nginx:latest
ENV NGINX_CONFIG=php
ENV NGINX_DEV_INSTALL=true
ENV PHP_FPM_UPSTREAM=wordpress:9000
ENV NGINX_SERVER_NAME=localhost
```

The container fails to start with this error: 
```bash
nginx: [emerg] unknown directive "max_fails=3" in /etc/nginx/upstream.d/proxy.conf:3
```

Maybe I'm just not following the docs correctly. Could you help me out?

**Comment by xthilakx** [comment]
Figured it out. I just had to set `PHP_FPM_UPSTREAM=wordpress:9000` to `PHP_FPM_UPSTREAM="server wordpress:9000"`

**Comment by tspicer** [comment]
can you do docker logs for the wordpress container? Would be curious what it says. Also, can you share your docker compose yml?

**Comment by xthilakx** [comment]
**First Dockerfile:**
```Dockerfile
FROM wordpress:php7.1-fpm-alpine
RUN mkdir -p /var/www/html/wp-content/themes/demo/
COPY . /var/www/html/wp-content/themes/demo/
```
**First docker-compose.yml:**
```yml
version: '3.7'

services:
  wordpress:
    build: .
    container_name: wordpress
    image: trao/wordpress
    restart: unless-stopped
    volumes:
      - thilak_root:/var/www/html
    networks:
      - proxy
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: 'super_secret'

networks:
  proxy:
    external: true

volumes:
  wordpress_root:
    external: true
```

**Second Dockerfile:**
```Dockerfile
FROM openbridge/nginx:latest
ENV NGINX_CONFIG=php
ENV NGINX_DEV_INSTALL=true
ENV PHP_FPM_UPSTREAM="wordpress:9000"
ENV NGINX_PROXY_UPSTREAM="wordpress:9000"
ENV REDIS_UPSTREAM="redis:6379"
ENV NGINX_SERVER_NAME=localhost
```
**Second docker-compose.yml:**
```yml
version: '3.7'

services:
  nginx:
    build: .
    restart: unless-stopped
    container_name: nginx
    ulimits:
      nproc: 65535
      nofile:
        soft: 49999
        hard: 99999
    tmpfs: /var/cache
    tty: true
    volumes:
      - type: volume
        source: wordpress_root
        target: /usr/share/nginx/html
        volume:
          nocopy: true
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    networks:
      - proxy
    environment:
      MYSQL_ROOT_PASSWORD: 'super_secret'
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  wordpress_root:
    external: true
  mysql:
    external: true
```
**Output of `docker logs` of WordPress container**
```bash
﻿﻿﻿WordPress not found in /var/www/html - copying now...
WARNING: /var/www/html is not empty! (copying anyhow)
Complete! WordPress has been successfully copied to /var/www/html
[28-Jan-2019 18:27:59] NOTICE: fpm is running, pid 1
[28-Jan-2019 18:27:59] NOTICE: ready to handle connections
```
