### ISSUE TITLE
"variables_hash_max_size" directive is duplicate

### ISSUE THREAD

**Issue by xavierdemoor** [openbridge/nginx#50]
**Describe the bug**
When I docker-compose up, I have this error before nginx exiting:

`2019/07/04 12:02:38 [emerg] 1#1: "variables_hash_max_size" directive is duplicate in /etc/nginx/conf.d/botblocker-nginx-settings.conf:18
`

**To Reproduce**
1. I just picked the docker-compose php example (and changing paths)

**Expected behavior**

**Additional context**
I'm using Docker for Windows

**Comment by tspicer** [comment]
Can you paste your compose file? Also, what is in the path you are mounting? For example, what base configs are you using?

**Comment by xdemoor** [comment]
**docker-compose.yml**
```
version: '3.1'
services:
  nginx:
    image: openbridge/nginx
    container_name: nginx
    depends_on:
      - redis
    ports:
      - 80:80
      - 443:443
    tty: true
    tmpfs: /var/cache
    restart: unless-stopped
    volumes:
      - ./conf/php/nginx:/conf/php/nginx
      - ./conf/php/monit:/conf/php/monit
      - ./web:/usr/share/nginx/html
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999
    env_file:
      - ./env/php.env
  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: redis
volumes:
  site:
```

I took the conf and env files from this repo. I didn't change anything in those files.
In my /web folder, I only have a index.php with phpinfo();
